tacertoforms/tacertoforms/Controllers/Relatorios/RelatorioAcessoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

using TaCertoForms.Attributes;
using TaCertoForms.Contexts;
using TaCertoForms.Controllers.Base;
using TaCertoForms.Models;

namespace TaCertoForms.Controllers {
	[SomenteLogado]
	public class RelatorioAcessoController : ControladoraBase {
		//relatório de acessos
		[Perfil(Perfil.Autor, Perfil.Administrador)]
		public ActionResult Relatorio1(string dataInicio, string dataFim) {
			DateTime DataInicio, DataFim;
			if(dataInicio == null) DataInicio = new DateTime(1900, 1, 1);
			else DataInicio = DateTime.Parse(dataInicio);
			if(dataFim == null) DataFim = DateTime.Now;
			else DataFim = DateTime.Parse(dataFim);

			List<Pessoa> alunos = Collection.PessoaList().Where(p => p.Perfil == Perfil.Aluno).ToList();
			if(alunos == null) alunos = new List<Pessoa>();

			List<int> alunosIds = new List<int>();
			foreach(var i in alunos)
				alunosIds.Add(i.IdPessoa);

			Context db = new Context();
			List<LogLogin> logs = db.LogLogin.Where(ll => alunosIds.Contains(ll.IdPessoa) && ll.HoraAcesso >= DataInicio && ll.HoraAcesso <= DataFim).ToList();
			if(logs == null) logs = new List<LogLogin>();

			List<int> meses = new List<int>() { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };

			List<ViewModelAcessos> vmAcessos = new List<ViewModelAcessos>();
			foreach(var a in alunos) {
				int cont = 0;
				ViewModelAcessos vma = new ViewModelAcessos();
				vma.id_pessoa = a.IdPessoa;
				vma.nome = a.Nome;
				foreach(var log in logs) {
					if(log.IdPessoa == a.IdPessoa) {
						cont++;
						if(vma.ultimo_acesso == null || vma.ultimo_acesso < log.HoraAcesso)
							vma.ultimo_acesso = log.HoraAcesso;
						if(log.HoraAcesso.Year == DateTime.Now.Year)
							meses[log.HoraAcesso.Month]++;
					}
				}
				vma.numero_acesso = cont;
				vmAcessos.Add(vma);
			}

			for(int i = meses.Count-1; i >= 0; i--)
				if(meses[i] == 0)
					meses.RemoveAt(i);
				else
					break;
			
			ViewBag.acessos = vmAcessos;
			ViewBag.acesso_mes = meses;

			return View();
		}
	}
}

tacertoforms/tacertoforms/Views/RelatorioAcesso/Relatorio1.cshtml
@{
    ViewBag.Title = "Relatório de Acessos";
}
@Styles.Render("~/Content/Chart.min.css")
@Scripts.Render("~/Scripts/Chart/Chart.bundle.min.js")
@Scripts.Render("~/Scripts/Chart/Chart.min.js")
@Scripts.Render("~/Scripts/Chart/Utils.chart.js")
<div class="content-wrapper">
    <section class="content-header">
        <h1>Relatório de Acessos</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")" data-toggle="tooltip" data-placement="bottom" data-original-title="Acesso a tela de boas vindas do sistema">Início</a></li>
            <li class="active"><a href="@Url.Action("Relatorios", "Home")" data-toggle="tooltip" data-placement="bottom" data-original-title="Acesso a tela de relatórios">Relatórios</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-warning collapsed-box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Filtros</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-plus"></i>
                            </button>
                        </div>
                    </div>
                    @using (Html.BeginForm("Relatorio1", "RelatorioAcesso", FormMethod.Get))
                    {
                        <div class="box-body">

                            <div class="form-group col-xs-12 col-md-3" data-toggle="tooltip" data-placement="bottom" data-original-title="Período em que a atividade ficará disponível para o aluno responder">
                                @Html.Label("A partir de:")
                                @Html.TextBox("dataInicio", null, new { @class = "form-control", @type = "text", @id = "dataInicial" })
                            </div>
                            <div class="form-group col-xs-12 col-md-3" data-toggle="tooltip" data-placement="bottom" data-original-title="Período em que a atividade ficará disponível para o aluno responder">
                                @Html.Label("Até:")
                                @Html.TextBox("dataFim", null, new { @class = "form-control", @type = "text", @id = "dataFinal" })
                            </div>
                        </div>
                    }
                    <div class="box-footer">
                        <input type="submit" value="Filtrar" class="btn btn-warning pull-right" />
                        <a href="@Url.Action("Relatorio1", "RelatorioAtividades")" class="btn btn-primary pull-right mr-button">Limpar filtros</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Relatório de acessos</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Aluno</th>
                                    <th>Quantidade de <br />acessos</th>
                                    <th>Último acesso</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var a in ViewBag.acessos)
                                {
                                    <tr>
                                        <td>@a.nome</td>
                                        <td>@a.numero_acesso</td>
                                        <td>@a.ultimo_acesso_string</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Relatório de acessos</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="content">
                            <div class="cl-height"><canvas id="chart-0"></canvas></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<script type="text/javascript">
    $('#example1').DataTable({
        "language": dados_translate
    });
</script>

<script>
    var dataArray = [
        @foreach(var m in ViewBag.acesso_mes)
        {
            @m @Html.Raw(",")
        }
    ];
    var presets = window.chartColors;
    var utils = Samples.utils;
    var inputs = {
        min: 0,
        max: 100,
        count: dataArray.length,
        continuity: 1
    };

    function generateLabels(config) {
        return utils.months(Chart.helpers.merge({
            count: inputs.count,
            section: 3
        }, config || {}));
    }

    var options = {
        maintainAspectRatio: false,
        spanGaps: false,
        elements: {
            line: {
                tension: 0.000001
            }
        },
        plugins: {
            filler: {
                propagate: false
            }
        },
        scales: {
            xAxes: [{
                ticks: {
                    autoSkip: false,
                    maxRotation: 0
                }
            }],
            yAxes: [{
                ticks: {
                    stepSize: 1
                }
            }]
        }
    };

    new Chart('chart-0', {
        type: 'line',
        data: {
            labels: generateLabels(),
            datasets: [{
                backgroundColor: utils.transparentize(presets.red),
                borderColor: presets.red,
                data: dataArray,
                label: 'Quantidade de acessos',
                fill: true
            }]
        },
        options: Chart.helpers.merge(options, {
            title: {
                text: 'Acessos de usuários por mês',
                display: true
            }
        })
    });
</script>

<style>
    .cl-height{height: 280px;}
</style>



<script>    
    $(document).ready(function () {

        $('#dataInicial').daterangepicker({
            singleDatePicker: true,
            timePicker: true,
            timePickerIncrement: 30,
            maxDate: new Date(Date.now()),
            locale: { format: 'DD/MM/YYYY hh:mm:ss' }
        });
        $('#dataFinal').daterangepicker({
            singleDatePicker: true,
            timePicker: true,
            timePickerIncrement: 30,
            locale: { format: 'DD/MM/YYYY hh:mm:ss' }
        });
    
    });    
</script>