tacertoforms/tacertoforms/Controllers/Relatorios/RelatorioAtividadesController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using TaCertoForms.Attributes;
using TaCertoForms.Contexts;
using TaCertoForms.Controllers.Base;
using TaCertoForms.Models;

namespace TaCertoForms.Controllers {
	[SomenteLogado]
	public class RelatorioAtividadesController : ControladoraBase {
		//relatório com todas as atividades do professor
		[Perfil(Perfil.Autor)]
		public ActionResult Relatorio1(int? IdTurma, int? IdDisciplina, bool? IsProva) {
			List<Turma> turmas = Collection.TurmaList();
			ViewBag.turmas = new SelectList(turmas, "IdTurma", "Serie");

			List<Disciplina> disciplinas = Collection.DisciplinaList();
			ViewBag.disciplinas = new SelectList(disciplinas, "IdDisciplina", "Nome");

			List<DisciplinaTurma> disciplinaTurmas = Collection.DisciplinaTurmaList();
			List<TurmaDisciplinaAutor> turmaDisciplinaAutors = Collection.TurmaDisciplinaAutorList();

			List<Atividade> atividades = Collection.AtividadeList();
			List<ViewModelAtividade> vmAtividades = new List<ViewModelAtividade>();
			foreach(var a in atividades) {
				int cont = vmAtividades.Count;

				TurmaDisciplinaAutor tda = turmaDisciplinaAutors.Where(aux => aux.IdTurmaDisciplinaAutor == a.IdTurmaDisciplinaAutor).FirstOrDefault();
				if(tda == null) continue;

				DisciplinaTurma dt = disciplinaTurmas.Where(aux => aux.IdDisciplinaTurma == tda.IdDisciplinaTurma).FirstOrDefault();
				if(dt == null) continue;

				if(IdTurma != null && dt.IdTurma != IdTurma) continue;
				if(IdDisciplina != null && dt.IdDisciplina != IdDisciplina) continue;
				if(IsProva != null && a.IsProva != IsProva) continue;

				vmAtividades.Add(new ViewModelAtividade());
				vmAtividades[cont].Atividade = a;

				vmAtividades[cont].nome_da_materia = ((Disciplina)(disciplinas.Where(aux => aux.IdDisciplina == dt.IdDisciplina).FirstOrDefault())).Nome;
				vmAtividades[cont].nome_da_turma = ((Turma)(turmas.Where(aux => aux.IdTurma == dt.IdTurma).FirstOrDefault())).Serie;
			}
			ViewBag.atividades = vmAtividades;

			return View();
		}

		//relatório de uma atividade especifica
		[Perfil(Perfil.Autor)]
		public ActionResult Relatorio2(int IdAtividade) {
			Atividade a = Collection.FindAtividade(IdAtividade);
			if(a == null) return HttpNotFound();
			TurmaDisciplinaAutor tda = Collection.FindTurmaDisciplinaAutor(a.IdTurmaDisciplinaAutor);
			if(tda == null) return HttpNotFound();
			DisciplinaTurma dt = Collection.FindDisciplinaTurma(tda.IdDisciplinaTurma);
			if(dt == null) return HttpNotFound();
			Disciplina d = Collection.FindDisciplina(dt.IdDisciplina);
			if(d == null) return HttpNotFound();
			Turma t = Collection.FindTurma(dt.IdTurma);
			if(t == null) return HttpNotFound();
			List<TurmaAluno> tas = Collection.TurmaAlunoList();
			if(tas == null) return HttpNotFound();
			List<int> alunos_id = new List<int>();
			foreach(var item in tas)
				if(item.IdTurma == t.IdTurma) alunos_id.Add(item.IdPessoa);

			Context db = new Context();
			List<AtividadeAluno> atividadeAlunos = db.AtividadeAluno.Where(aa => aa.IdAtividade == IdAtividade).ToList();
			if(atividadeAlunos == null) atividadeAlunos = new List<AtividadeAluno>();

			List<ViewModelAtividadeAluno> vmAtividadeAlunos = new List<ViewModelAtividadeAluno>();
			double nota = 0;
			foreach(var aa in atividadeAlunos) {
				ViewModelAtividadeAluno aa_aux = new ViewModelAtividadeAluno();
				aa_aux.AtividadeAluno = aa;
				aa_aux.nome_aluno = (Collection.FindPessoa(aa.IdPessoa))?.Nome;
				vmAtividadeAlunos.Add(aa_aux);
				nota += aa.MaiorNota;
			}
			nota /= atividadeAlunos.Count;

			ViewModelAtividade vmAtividade = new ViewModelAtividade();
			vmAtividade.Atividade = a;
			vmAtividade.nome_da_materia = d.Nome;
			vmAtividade.nome_da_turma = t.Serie;
			vmAtividade.media_nota = nota;

			ViewBag.atividade = vmAtividade;
			ViewBag.alunos = vmAtividadeAlunos;

			return View();
		}

        [HttpGet]
        [Perfil(Perfil.Autor)]
        public ActionResult AjaxDisciplinas(int? IdTurma, int? Selected) {
            List<DisciplinaTurma> disciplinaTurmas = Collection.DisciplinaTurmaList();
            List<Disciplina> disciplinas = new List<Disciplina>();
            foreach(var dt in disciplinaTurmas)
                if(dt.IdTurma == IdTurma)
                    disciplinas.Add(Collection.FindDisciplina(dt.IdDisciplina));
            ViewBag.Disciplinas = new SelectList(disciplinas, "IdDisciplina", "Nome", Selected);
            return View();
        }
    }
}

tacertoforms/tacertoforms/Views/RelatorioAtividades/AjaxDisciplinas.cshtml
@{
    Layout = null;
}

@Html.Label("Disciplina")
@Html.DropDownList("IdDisciplina",
ViewBag.Disciplinas as SelectList,
"Disciplina",
new { @class = "form-control"})

tacertoforms/tacertoforms/Views/RelatorioAtividades/Relatorio1.cshtml
@{
    ViewBag.Title = "Relatório de Atividades";
}
@Styles.Render("~/Content/Chart.min.css")
<div class="content-wrapper">
    <section class="content-header">
        <h1>
            Relatório de Atividades
        </h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")" data-toggle="tooltip" data-placement="bottom" data-original-title="Acesso a tela de boas vindas do sistema">Início</a></li>
            <li class="active"><a href="@Url.Action("Relatorios", "Home")" data-toggle="tooltip" data-placement="bottom" data-original-title="Acesso a tela de relatórios">Relatórios</a></li>
        </ol>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box box-warning collapsed-box">
                    <div class="box-header with-border">
                        <h3 class="box-title">Filtros</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-plus"></i>
                            </button>
                        </div>
                    </div>
                    @using (Html.BeginForm("Relatorio1", "RelatorioAtividades", FormMethod.Get))
                    {
                        <div class="box-body">
                            <div class="form-group col-xs-12 col-md-4">
                                @Html.Label("Turma")
                                @Html.DropDownList("IdTurma",
                                ViewBag.turmas as SelectList,
                                "Turma",
                                new { @class = "form-control", @id = "turma" })
                            </div>
                            <div class="form-group col-xs-12 col-md-4">
                                <div class="disciplinas">
                                    @Html.Label("Disciplina")
                                    @Html.DropDownList("IdDisciplina",
                                    new SelectList(new List<String>()),
                                    "Disciplina",
                                    new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group col-xs-12 col-md-4">
                                @Html.Label("É prova?")
                                @Html.DropDownList("IsProva",
                                new List<SelectListItem> {
                                    new SelectListItem() { Text = "Todos", Value = ""},
                                    new SelectListItem() { Text = "Sim", Value = true.ToString()},
                                    new SelectListItem() { Text = "Não", Value = false.ToString()}
                                },
                                null,
                                new { @class = "form-control" })
                            </div>
                        </div>
                    }
                    <div class="box-footer">
                        <input type="submit" value="Filtrar" class="btn btn-warning pull-right" />
                        <a href="@Url.Action("Relatorio1", "RelatorioAtividades")" class="btn btn-primary pull-right mr-button">Limpar filtros</a>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Selecione a atividade</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <table id="example1" class="table table-bordered  table-striped table-relatorio">
                            <thead>
                                <tr>
                                    <th>Atividade</th>
                                    <th>Turma</th>
                                    <th>Disciplina</th>
                                    <th>Início da Atividade</th>
                                    <th>Fim da Atividade</th>
                                    <th>Número de Tentativas</th>
                                    <th>É prova</th>
                                    <th>Número de Questões</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach(var a in ViewBag.atividades)
                                {
                                    <tr>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.Titulo</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.nome_da_turma</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.nome_da_materia</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.DataInicio.ToString()</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.DataFim.ToString()</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.NumeroTentativas</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@(a.IsProva ? "Sim" : "Não")</a>
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Relatorio2", "RelatorioAtividades", new { IdAtividade = a.IdAtividade })">@a.NumeroQuestoes</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

@Scripts.Render("~/Scripts/Chart/Chart.bundle.min.js")
@Scripts.Render("~/Scripts/Chart/Chart.min.js")



<script type="text/javascript">
    $('#example1').DataTable({
        "language": dados_translate
    });
    $('#periodo').daterangepicker({
        locale: { format: 'DD/MM/YYYY' }
    });

    $('#turma').on('change', function () {
        var IdDisciplina = new URLSearchParams(window.location.search).get('IdDisciplina');
        $.ajax({
            url: '@Url.Action("AjaxDisciplinas", "RelatorioAtividades")',
            data: {
                IdTurma: $('#turma').val(),
                Selected: IdDisciplina
            },
            cache: false,
            type: 'get',
            success: function (data) {
                $('.disciplinas').html(data);
            },
            error: function () {
                alert('Ocorreu algum erro de conexão. Por favor, tente novamente mais tarde');
            }
        });
    }).change();
</script>


<style>
    div.dataTables_wrapper div.dataTables_filter { margin-right: 0 !important;}
</style>

tacertoforms/tacertoforms/Views/RelatorioAtividades/Relatorio2.cshtml
@{
    ViewBag.Title = "Relatório de Notas de Alunos";
}
@Styles.Render("~/Content/Chart.min.css")
@Scripts.Render("~/Scripts/Chart/Utils.chart.js")
@Scripts.Render("~/Scripts/Chart/Chart.bundle.min.js")
@Scripts.Render("~/Scripts/Chart/Chart.min.js")
<div class="content-wrapper">
    <section class="content-header">
        <h1>Relatório de Notas</h1>
        <ol class="breadcrumb">
            <li><a href="@Url.Action("Index", "Home")" data-toggle="tooltip" data-placement="bottom" data-original-title="Acesso a tela de boas vindas do sistema">Início</a></li>
            <li class="active"><a href="@Url.Action("Relatorios", "Home")" data-toggle="tooltip" data-placement="bottom" data-original-title="Acesso a tela de relatórios">Relatórios</a></li>
        </ol>
    </section>
    <section class="content relatorios">
        <div class="row">
            <div class="col-lg-4 col-xs-6">
                <div class="small-box bg-aqua">
                    <div class="inner">
                        <h3>@ViewBag.atividade.nome_da_turma</h3>
                        <p>Turma</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-users"></i>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-xs-6">
                <div class="small-box bg-green">
                    <div class="inner">
                        <h3>@ViewBag.atividade.nome_da_materia</h3>
                        <p>Disciplina</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-file-o"></i>
                    </div>
                </div>
            </div>

            <div class="col-lg-4 col-xs-6">
                <div class="small-box bg-yellow">
                    <div class="inner">
                        <h3>@ViewBag.atividade.media_nota.ToString("N2")</h3>
                        <p>Média da Turma</p>
                    </div>
                    <div class="icon">
                        <i class="fa fa-tags"></i>
                    </div>
                </div>
            </div>         
            <div class="col-md-8">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Relatório de notas de alunos</h3>                        
                    </div>
                    <div class="box-body">
                        <table id="example1" class="table table-bordered  table-striped">
                            <thead>
                                <tr>
                                    <th>Aluno</th>
                                    <th>Número de Tentativas</th>
                                    <th>Maior Nota</th>
                                    <th>Menor Tempo</th>
                                    <th>Maior Tempo</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var a in ViewBag.alunos)
                                {
                                    <tr>
                                        <td>@a.nome_aluno</td>
                                        <td>@a.NumeroTentativas</td>
                                        <td>@a.MaiorNota.ToString("N2")</td>
                                        <td>@a.menor_tempo</td>
                                        <td>@a.maior_tempo</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Média da turma</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse">
                                <i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        <div id="canvas-holder">
                            <canvas id="chart-area"></canvas>
                            <div class="row">
                                <div class="col-md-4 mt20">
                                    @Html.Label("Média da escola")
                                    @Html.TextBox("Media", 6, new { @class = "form-control", @type = "number", @step = ".1", @min = "1", @id = "media", @value = "6.0" })                                    
                                </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>






<script type="text/javascript">
    //Media = .replace(".", ",")
    var flagPrimeiraVez = true;
    function AtualizarMedia() {
        var media = parseInt(document.getElementById("media").value);
        var acimaDaMedia = 0;
        for(var i=0; i<notas.length; i++)
            if(notas[i] >= media) acimaDaMedia++;
        
        config.data.datasets[0].data[0] = acimaDaMedia;
        config.data.datasets[0].data[1] = notas.length - acimaDaMedia;

        var ctx = document.getElementById('chart-area').getContext('2d');
        console.log(window.myPie);
        if(flagPrimeiraVez){
            window.myPie = new Chart(ctx, config);
            flagPrimeiraVez = false;
        }
        else{
            window.myPie.destroy();
            window.myPie = new Chart(ctx, config);
            //window.myPie.set("data", config.data, true);
        }
        window.myPie.render();
    };

    $('#example1').DataTable({
        "language": dados_translate
    });

    var notas =  [
        @foreach(var a in ViewBag.alunos)
        {
            @Html.Raw("parseFloat('")
            @a.MaiorNota
            @Html.Raw("'),")
        }
    ];

    var config = {
        type: 'pie',
        data: {
            datasets: [{
                data: [
                    8.0,
                    2.0
                ],
                backgroundColor: [
                    window.chartColors.blue,
                    window.chartColors.red
                ]
            }],
            labels: [
                'Acima da média',
                'Abaixo da média'
            ]
        },
        options: {
            responsive: true
        }
    };

    window.onload = ()=>{ AtualizarMedia();};
    document.getElementById("media").onchange = ()=>{AtualizarMedia()};
</script>

<style>
    div.dataTables_wrapper div.dataTables_filter {
        margin-right: 0 !important;
    }
</style>