tacertoforms/tacertoforms/Controllers/TurmaController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web.Mvc;

using TaCertoForms.Attributes;
using TaCertoForms.Controllers.Base;
using TaCertoForms.Models;

namespace TaCertoForms.Controllers {
    [SomenteLogado]
    public class TurmaController : ControladoraBase {
        [Perfil(Perfil.Administrador)]
        public ActionResult Index() {
            List<Instituicao> list = Collection.InstituicaoList();
            if (list == null)
                list = new List<Instituicao>();
            ViewBag.InstituicaoList = list;
            return View(Collection.TurmaList());
        }

        [Perfil(Perfil.Administrador)]
        public ActionResult Create() {
            List<Instituicao> list = Collection.InstituicaoList();
            ViewBag.InstituicaoList = new SelectList(list, "IdInstituicao", "NomeFantasia");
            return View();
        }

        [HttpPost]
        [Perfil(Perfil.Administrador)]
        public ActionResult Create(Turma turma) {
            if(Collection.CreateTurma(turma) != null) {
                TempData["success"] = "Turma cadastrada com sucesso.";
                return RedirectToAction("Index");
            }
            return View(turma);
        }

        [Perfil(Perfil.Administrador)]
        public ActionResult Edit(int? id) {
            if(id == null) {
                TempData["error"] = "Ocorreu um erro inesperado. Entre em contato com o administrador do sistema.";
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turma turma = Collection.FindTurma(id);
            if(turma == null) {
                TempData["error"] = "Você não tem permissão para editar esta turma.";
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            };
            List<Instituicao> list = Collection.InstituicaoList();
            ViewBag.InstituicaoList = new SelectList(list, "IdInstituicao", "NomeFantasia");
            return View(turma);
        }

        [HttpPost]
        [Perfil(Perfil.Administrador)]
        public ActionResult Edit(Turma turma) {
            if(Collection.EditTurma(turma) != null) {
                TempData["success"] = "Turma atualizada com sucesso.";
                return RedirectToAction("Index");
            }
            return View(turma);
        }

        /*[Perfil(Perfil.Administrador)]
        public ActionResult Delete(int? id) {
            if(id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            Turma turma = Collection.FindTurma(id);
            if(turma == null) return new HttpStatusCodeResult(HttpStatusCode.NotFound);

            Instituicao instituicao = Collection.FindInstituicao(turma.IdInstituicao);
            ViewBag.NomeFantasia = instituicao.NomeFantasia;

            return View(turma);
        }

        [Perfil(Perfil.Administrador)]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id) {
            Collection.DeleteTurma(id);
            return RedirectToAction("Index");
        }*/

        //######################### AJAX (Turma Disciplina) #########################
        [HttpGet]
        [Perfil(Perfil.Administrador, Perfil.Autor)]
        public ActionResult AjaxTurmas(int IdInstituicao, string scope = "") {
            List<Turma> turmas = Collection.TurmaList()?.Where(t => t.IdInstituicao == IdInstituicao).ToList();
            if(turmas == null) turmas = new List<Turma>();
            ViewBag.TurmasList = new SelectList(turmas, "IdTurma", "Serie");
            ViewBag.Scope = scope;
            return View();
        }

        /*
        [HttpGet]
        [Perfil(Perfil.Administrador)]
        public ActionResult AjaxTurmasDisciplinas(int IdAutor) {
            List<ViewModelDisciplina> disciplinaTurma = new List<ViewModelDisciplina>();
            List<TurmaDisciplinaAutor> turmaDisciplinaProf = Collection.TurmaDisciplinaAutorList()?.Where(tda => tda.IdAutor == IdAutor).ToList();

            foreach(var td in turmaDisciplinaProf) {
                List<DisciplinaTurma> dt = Collection.DisciplinaTurmaList()?.Where(dta => dta.IdDisciplinaTurma == td.IdDisciplinaTurma).ToList();
                foreach(var discTurm in dt) {
                    Disciplina disciplina = Collection.FindDisciplina(discTurm.IdDisciplina);
                    ViewModelDisciplina vmDisc = new ViewModelDisciplina() { Nome = disciplina.Nome, IdTurmaDisciplinaAutor = td.IdTurmaDisciplinaAutor };
                    vmDisc.Turmas.Add(Collection.FindTurma(discTurm.IdTurma));
                    disciplinaTurma.Add(vmDisc);
                }
            }
            return View(disciplinaTurma);
        }
        */

        [HttpGet]
        [Perfil(Perfil.Administrador)]
        public ActionResult AjaxTurmasDisciplinas(int IdAutor) {
            List<ViewModelDisciplina> disciplinaTurma = new List<ViewModelDisciplina>();
            List<TurmaDisciplinaAutor> turmaDisciplinaProf = Collection.TurmaDisciplinaAutorList()?.Where(tda => tda.IdAutor == IdAutor).ToList();
            if(turmaDisciplinaProf == null) return null;
            foreach(var td in turmaDisciplinaProf) {
                List<DisciplinaTurma> dt = Collection.DisciplinaTurmaList()?.Where(dta => dta.IdDisciplinaTurma == td.IdDisciplinaTurma).ToList();
                foreach(var discTurm in dt){
                    Disciplina disciplina = Collection.FindDisciplina(discTurm.IdDisciplina);
                    ViewModelDisciplina vmDisc = new ViewModelDisciplina() { Nome = disciplina.Nome, IdTurmaDisciplinaAutor = td.IdTurmaDisciplinaAutor };
                    vmDisc.Turmas.Add(Collection.FindTurma(discTurm.IdTurma));
                    disciplinaTurma.Add(vmDisc);
                }
            }
            return View(disciplinaTurma);
        }

        [HttpPost]
        [Perfil(Perfil.Administrador)]
        public void SalvarTurmaDisciplina(TurmaDisciplinaAutor turmaDisciplina) {            
            Collection.CreateTurmaDisciplinaAutor(turmaDisciplina);
            TempData["success"] = "Registro cadastrado com sucesso.";
        }

        [HttpPost]
        [Perfil(Perfil.Administrador)]
        public void AjaxDesvincularTurmaDisciplina(int id) {
            Collection.DeleteTurmaDisciplinaAutor(id);
            TempData["success"] = "Desvínculo realizado com sucesso.";
        }

        //######################### AJAX Alunos #########################
        //POST: Ajax
        [HttpPost]
        [Perfil(Perfil.Administrador)]
        public void SalvarTurmaAluno(TurmaAluno turmaAluno) {
            Collection.CreateTurmaAluno(turmaAluno);
            TempData["success"] = "Registro cadastrado com sucesso.";
        }

        [HttpGet]
        [Perfil(Perfil.Administrador)]
        public ActionResult AjaxTurmasAlunos(int IdPessoa) {
            List<TurmaAluno> turmaAluno = Collection.TurmaAlunoList();
            if(turmaAluno != null) turmaAluno = turmaAluno.Where(ta => ta.IdPessoa == IdPessoa).ToList();
            List<ViewModelPessoa> aluno = new List<ViewModelPessoa>();

            if(turmaAluno != null)
                foreach(var ta in turmaAluno) {
                    ViewModelPessoa vmAluno = new ViewModelPessoa() { IdTurmaAluno = ta.IdTurmaAluno };
                    vmAluno.Turma.Add(Collection.FindTurma(ta.IdTurma));
                    aluno.Add(vmAluno);
                }
            return View(aluno);
        }

        //Desvincular turma e aluno
        [HttpPost]
        [Perfil(Perfil.Administrador)]
        public void AjaxDesvincularTurmaAluno(int id) {
            Collection.DeleteTurmaAluno(id);
            TempData["success"] = "Desvínculo realizado com sucesso.";
        }
    }
}

tacertoforms/tacertoforms/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@ViewBag.Title</title>
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/Ionicons/css/ionicons.min.css")
    @Styles.Render("~/Content/jquery-jvectormap.css")
    @Styles.Render("~/Content/AdminLTE.min.css")
    @Styles.Render("~/Content/blue.css")
    @Styles.Render("~/Content/skin-blue.min.css")
    @Styles.Render("~/Content/admin.css")
    @Styles.Render("~/Content/dataTables.bootstrap.min.css")
    @Styles.Render("~/Content/jquery.fancybox.min.css")
    @Styles.Render("~/Content/daterangepicker.css")
    @Styles.Render("~/Content/iCheck/all.css")
    @Styles.Render("~/Content/select2.min.css")

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">

        <header class="main-header">
            <!-- Logo -->
            <a href="#" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><img src="~/Content/images/LOGO-ABERTURA.png"></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><img src="~/Content/images/LOGO-ABERTURA2.png"></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown user user-menu">
                            <a href="@Url.Action("Edit", "Pessoa", new { id = Session["IdPessoa"]})" data-toggle="tooltip" data-placement="bottom" data-original-title="Alterar informações de cadastro e perfil">
                                <i class="fa fa-user"></i>
                                @if (@Session["FotoPerfil"] != null)
                                {
                                    <img src="~/Content/images/upload/@Session["FotoPerfil"]" class="user-image" alt="User Image">
                                }

                                @Session["NomeUsuario"]
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("LogOff", "Login")" data-toggle="tooltip" data-placement="bottom" data-original-title="Fazer logoff do sistema"><i class="fa fa-external-link"></i></a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div class="pull-left info">
                        <p>Área administrativa</p>
                    </div>
                </div>
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MENU DE NAVEGAÇÃO</li>
                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> <span>Início</span></a></li>


                    @if (Session["Perfil"].Equals(Perfil.Administrador))
                    {
                        <li><a href="@Url.Action("Index", "Relatorio")"><i class="fa fa-tasks"></i> <span>Relatórios</span></a></li>
                        <li><a href="@Url.Action("Index", "Instituicao")"><i class="fa fa-institution"></i> <span>Instituições</span></a></li>

                        <li><a href="@Url.Action("Index", "Pessoa")"><i class="fa fa-user"></i><span>Usuários</span></a></li>
                        <li><a href="@Url.Action("Index", "Turma")"><i class="fa fa-users"></i> <span>Turmas</span></a></li>
                        <li><a href="@Url.Action("Index", "Disciplina")"><i class="fa fa-reorder"></i> <span>Disciplinas</span></a></li>
                    }

                    @if (Session["Perfil"].Equals(Perfil.Autor))
                    {
                        <li><a href="@Url.Action("RelatorioProfessorIndex", "Relatorio")"><i class="fa fa-tasks"></i> <span>Relatórios</span></a></li>
                        <li><a href="@Url.Action("Index", "Atividade")"><i class="fa fa-th-list"></i> <span>Atividades</span></a></li>
                    }
                    <li><a href="@Url.Action("LogOff", "Login")"><i class="fa fa-external-link"></i> <span>Sair</span></a></li>
                </ul>
            </section>
        </aside>
        @Scripts.Render("~/Scripts/jquery.min.js")
        @Scripts.Render("~/Scripts/bootstrap.min.js")
        @Scripts.Render("~/Scripts/fastclick.js")
        @Scripts.Render("~/Scripts/adminlte.min.js")
        @Scripts.Render("~/Scripts/jquery.sparkline.min.js")
        @Scripts.Render("~/Scripts/jquery-jvectormap-1.2.2.min.js")
        @Scripts.Render("~/Scripts/jquery-jvectormap-world-mill-en.js")
        @Scripts.Render("~/Scripts/jquery.slimscroll.min.js")
        @Scripts.Render("~/Scripts/Chart.js")
        @Scripts.Render("~/Scripts/demo.js")
        @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
        @Scripts.Render("~/Scripts/dataTables.bootstrap.min.js")
        @Scripts.Render("~/Scripts/jquery.fancybox.min.js")
        @Scripts.Render("~/Scripts/moment.min.js")
        @Scripts.Render("~/Scripts/daterangepicker.js")
        @Scripts.Render("~/Scripts/moment-with-locales.min.js")
        @Scripts.Render("~/Scripts/jquery.inputmask.js")
        @Scripts.Render("~/Scripts/jquery.inputmask.date.extensions.js")
        @Scripts.Render("~/Scripts/jquery.inputmask.extensions.js")
        @Scripts.Render("~/Scripts/cidades-estados.js")
        @Scripts.Render("~/Scripts/busca-cep.js")
        @Scripts.Render("~/Scripts/icheck.min.js")
        @Scripts.Render("~/Scripts/select2.min.js")
        @Scripts.Render("~/Scripts/functions.js")

        @RenderSection("scripts", required: false)
        <input type="hidden" id="success" value="@TempData["success"]" />
        <input type="hidden" id="info" value="@TempData["info"]" />
        <input type="hidden" id="warning" value="@TempData["warning"]" />
        <input type="hidden" id="error" value="@TempData["error"]" />

        <script>
            $(function () {
                var displayMessage = function (message, msgType) {
                    $('.alert-message').html(
                        '<div class="alert alert-' + msgType + ' alert-dismissible alert-return">' +
                        '<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>'
                        + message +
                        '</div>'
                    );
                    setTimeout(function () {
                        $('.alert-return').alert('close');
                    }, 6000);
                };

                if ($('#success').val()) {
                    displayMessage($('#success').val(), 'success');
                }
                if ($('#info').val()) {
                    displayMessage($('#info').val(), 'info');
                }
                if ($('#warning').val()) {
                    displayMessage($('#warning').val(), 'warning');
                }
                if ($('#error').val()) {
                    displayMessage($('#error').val(), 'error');
                }
            });
        </script>

        @RenderBody()

        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Versão</b> 2.4.18
            </div>
            <strong>Copyright &copy; @DateTime.Now.Year - STARTUP/SESI</strong> Todos os direitos reservados.
        </footer>
        <div class="control-sidebar-bg"></div>
    </div>    
</body>
</html>